test: Test that error traces from 'verify' are reproducible in 'sim'.

diff --git a/test/lib/check b/test/lib/check
--- a/test/lib/check
+++ b/test/lib/check
@@ -170,6 +170,11 @@ verify() {
             echo "# expected error to be found at $location, but it was not"
             exit 1
         fi
+        if ! grep -q "^  @location: $location" sim.out; then
+            nl -ba "$1"
+            echo "# expected error to be found in divine sim at $location, but it was not"
+            exit 1
+        fi
     else
         if ! grep -q "no errors found" verify.out &&
            ! grep -q "no states produced" verify.out; then
