test: Abolish divcheck-wrap.

diff --git a/test/lib/check b/test/lib/check
--- a/test/lib/check
+++ b/test/lib/check
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-if test -z "$EXPORT"; then
+if test -z "$DIVCHECK_MODE"; then
     set -e
     . util
 fi
@@ -167,7 +167,8 @@ warn_table()
 }
 
 verify() {
-    grep -s table verify.out | sed -re 's@.*\{ used: ([0-9]+), capacity: ([0-9]+) \}@\1 \2@' | \
+    test -n "$DIVCHECK_MODE" ||
+        grep table verify.out | sed -re 's@.*\{ used: ([0-9]+), capacity: ([0-9]+) \}@\1 \2@' | \
         while read used capacity; do
             case $capacity in
                 256) ;; # nothing
@@ -179,7 +180,7 @@ verify() {
         done
     if fgrep -q '/* ERRSPEC:' "$1"; then
         spec=$(fgrep '/* ERRSPEC:' $1 | cut -d: -f2- | sed -e "s,^ *,," -e "s, *\*/,,")
-        if test -n "$EXPORT"; then exit 1; fi
+        if test -n "$DIVCHECK_MODE"; then exit 1; fi
         echo spec: $spec
         if ! perl $TESTS/lib/check-errspec "$spec" verify.out; then
             echo "# expected error to be found in $spec, but it was not"
@@ -187,7 +188,7 @@ verify() {
         fi
     elif fgrep -q '/* ERROR' "$1"; then
         location=`fgrep -Hn '/* ERROR' "$1" | cut -d: -f1-2`
-        if test -n "$EXPORT"; then
+        if test -n "$DIVCHECK_MODE"; then
             echo "expect --result error --location $location";
             exit 0
         fi
@@ -219,14 +220,14 @@ verify() {
             exit 1
         fi
     elif fgrep -q '/* BOOT ERROR */' "$1"; then
-        if test -n "$EXPORT"; then echo "expect --result boot-error"; exit 0; fi
+        if test -n "$DIVCHECK_MODE"; then echo "expect --result boot-error"; exit 0; fi
         if ! grep -q "error found: boot" verify.out; then
             nl -ba "$1"
             echo "# boot error was expected but was not found"
             exit 1
         fi
     else
-        if test -n "$EXPORT"; then echo "expect --result valid"; exit 0; fi
+        if test -n "$DIVCHECK_MODE"; then echo "expect --result valid"; exit 0; fi
         if ! grep -q "error found: no" verify.out; then
             nl -ba "$1"
             grep '^    location' verify.out || true
diff --git a/test/lib/verify b/test/lib/verify
--- a/test/lib/verify
+++ b/test/lib/verify
@@ -1,20 +1,47 @@
-#!/bin/sh
+#!/bin/bash
 # -*- sh -*-
 
+# When running manually:
+#   export mode (--export): cwd in source root, no variables should be needed
+#   test mode (no flag): cwd in {build directory}/test, set the following variables:
+#       OBJ, SRCDIR, BINDIR and optionally TEST_FLAVOUR.
+set -e
+
 if test "$1" = "--export"; then
+    # Only export the divcheck-readable script (this is used by divbench-import)
     EXPORT=1
     shift
-    set -e
-else
-    test -e lib/testcase && SILENT=1 . lib/testcase
-    EXPORT= # unset
-fi
-export EXPORT
 
-run()
-{
-    if test -n "$EXPORT"; then echo "$@"; else echo "+ divine $@"; divine "$@"; fi
-}
+    test -n "$OBJ" || export OBJ=$(make show var=OBJ)
+    test -n "$SRCDIR" || export SRCDIR="$PWD"
+    test -n "$BINDIR" || export BINDIR="${OBJ}debug" #TODO: default flavour
+
+    addcmds()
+    {
+        cat
+    }
+
+    addcmd()
+    {
+        echo "$@"
+    }
+
+else
+    EXPORT= # unset
+    dcscript=testcase.divcheck
+    # some tests call this already inside correct working directory
+    test ! -r lib/testcase || . lib/testcase
+
+    addcmds()
+    {
+        cat >> $dcscript
+    }
+    addcmd()
+    {
+        echo "$@" >> $dcscript
+    }
+
+fi
 
 getopt() { perl -ne "print \$1 if (m,/\* $1: (.*?) \*/, or m,// $1: (.*?)\n,)" $2; }
 
@@ -48,61 +75,83 @@ fi
 if test -z "$EXPORT"; then
     if echo "$opts" | grep -q "symbolic"; then
         solver=$TEST_FLAVOUR
-        if test $solver = z3 && test $OPT_Z3 = OFF; then skip; fi
-        if test $solver = stp && test $OPT_STP = OFF; then skip; fi
-        if test $solver = smtlib; then solver=$solver:z3; z3 --version > /dev/null || skip; fi
-        if test $solver = vanilla; then solver=none; fi
-        extra="$extra --solver $solver"
+        if test "$solver" = z3 && test $OPT_Z3 = OFF; then skip; fi
+        if test "$solver" = stp && test $OPT_STP = OFF; then skip; fi
+        if test "$solver" = smtlib; then solver=$solver:z3; z3 --version > /dev/null || skip; fi
+        if test "$solver" = vanilla; then solver=none; fi
+        if test -n "$solver" ; then
+            extra="$extra --solver $solver";
+        fi
     elif ! echo "$opts" | egrep -q "leakcheck|relaxed"; then
         # --symbolic currently leaks memory
         extra="$extra --leakcheck exit"
     fi
 fi
 
-if test -n "$EXPORT"; then
-    dir=$(dirname $1)
-    name=$(basename $1)
-    dios=$SRCDIR/dios
-    incs="-isystem $dios/include -isystem $dios/libcxx/include"
-    incs="$incs -isystem $BINDIR/dios/include" #generated headers: hostabi.h etc.
-    incs="$incs -I $SRCDIR/bricks"
-    for f in $name $extrasrc; do
-        deps=$(cd $dir && clang -I. $incs $std -MM -MT "" $f | sed -e 's,^: [^ ]*,,' -e 's,\\$,,')
-        echo load $dir/$f $f
-        for dep in $deps; do
-            if ! echo $dep | grep -q '^/'; then dep=$dir/$dep; fi
-            echo load $dep $(echo $dep | sed -re "s,$dir/*,,")
-        done
+# Generate 'load' commands
+dir=$(dirname $1)
+name=$(basename $1)
+dios=$SRCDIR/dios
+incs="-isystem $dios/include -isystem $dios/libcxx/include"
+incs="$incs -isystem $BINDIR/dios/include" #generated headers: hostabi.h etc.
+incs="$incs -I $SRCDIR/bricks"
+for f in $name $extrasrc; do
+    deps=$(cd $dir && clang -I. $incs $std -MM -MT "" $f | \
+        sed -e 's,^: [^ ]*,,' -e 's,\\$,,') || true
+    addcmd load $dir/$f $f
+    for dep in $deps; do
+        if ! echo $dep | grep -q '^/'; then dep=$dir/$dep; fi
+        addcmd load $dep $(echo $dep | sed -re "s,$dir/*,,")
     done
-    if test -z "$expect"; then
-        check=$(readlink -f $(dirname $0)/check)
-        (cd $dir ; $check verify $name)
-    else
-        echo "expect" "$expect"
-    fi
+done
+
+# Generate 'expect' commands (see also test/lib/check verify)
+if test -z "$expect"; then
+    check=$(readlink -f $(dirname $0)/check)
+    chmod +x "$check"
+    export DIVCHECK_MODE=1
+    (cd $dir ; $check verify $name) | addcmds
 else
-    name="$1"
+    addcmd "expect" "$expect"
 fi
 
+# Generate 'cc' command
 if test "$skipcc" = 1; then
     run=$name
     opts="$std $opts"
 else
-    run cc -o testcase.bc $std $ccopt "$name" $gtest
+    addcmd cc -o testcase.bc $std $ccopt "$name" $gtest
     run=testcase.bc
 fi
 
-run verify $resources $extra $opts $run $args
+# Generate 'verify' command
+addcmd verify $resources $extra $opts $run $args
 
 if test -n "$EXPORT"; then exit 0; fi
+
+cat $dcscript | sed -e 's,^,  | ,'
+
+# Run divcheck with the script
+divcheck $dcscript
 
 err=$(grep "error found:" verify.out | cut -d' ' -f3- || true)
 if [ "$err" = yes ]; then
     echo "+ divine sim --batch --skip-init --load-report verify.out"
     echo "backtrace" | \
-        divine sim --batch --skip-init --load-report verify.out > sim.out 2>&1
+        divine sim --batch --skip-init --load-report verify.out 2>&1 | tee sim.out
+
+    getarg() { perl -ne "print \$1 if m/--$1 +(\\S*)/" $2; }
+    location=`getarg location $dcscript`
+    symbol=`getarg symbol $dcscript`
+    if test -n "$location" && ! grep -q "^  [{}a-zA-Z_].* at $location" sim.out; then
+            echo "# expected error to be found in divine sim at $location, but it was not"
+            exit 1
+    elif test -n "$symbol" && ! grep -qP "^  \\S*$symbol.* at .*" sim.out; then
+            echo "# expected error to be found in divine sim in $symbol, but it was not"
+            exit 1
+    fi
 fi
 
-check verify "$name"
+exit 0;
 
 # vim: syntax=sh
